version: '3.8'

services:
  # PostgreSQL database with pgvector extension
  postgres:
    image: pgvector/pgvector:pg16
    container_name: doc-server-postgres-dev
    environment:
      POSTGRES_DB: docs
      POSTGRES_USER: docserver
      POSTGRES_PASSWORD: development_password_change_in_production
    ports:
      - "5433:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./sql/init:/docker-entrypoint-initdb.d
    networks:
      - doc-server-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docserver -d docs"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev_data:
    driver: local

networks:
  doc-server-network:
    driver: bridge