---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-actions-deployment-manager
  namespace: mcp
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "patch", "update", "rollout"]
- apiGroups: ["apps"]
  resources: ["deployments/scale"]
  verbs: ["get", "patch", "update"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments/rollback"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-actions-deployment-binding
  namespace: mcp
subjects:
- kind: ServiceAccount
  name: k8s-runner-gha-rs-no-permission
  namespace: arc-runners
roleRef:
  kind: Role
  name: github-actions-deployment-manager
  apiGroup: rbac.authorization.k8s.io
