# Rust formatting configuration for Doc Server

# Edition and features
edition = "2021"
unstable_features = false

# Code style
max_width = 100
hard_tabs = false
tab_spaces = 4

# Imports
imports_granularity = "Crate"
reorder_imports = true
group_imports = "StdExternalCrate"

# Functions and control flow
fn_args_layout = "Tall"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"

# Comments and documentation
wrap_comments = true
format_code_in_doc_comments = true
normalize_comments = true
normalize_doc_attributes = true

# Strings and arrays
format_strings = true
format_macro_matchers = true

# Trailing elements
trailing_comma = "Vertical"
trailing_semicolon = true

# Blank lines
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0

# Misc
newline_style = "Unix"
use_small_heuristics = "Default"