apiVersion: batch/v1
kind: Job
metadata:
  name: doc-server-migration
  namespace: default
  labels:
    app: doc-server
    component: migration
spec:
  template:
    metadata:
      labels:
        app: doc-server
        component: migration
    spec:
      restartPolicy: Never
      containers:
      - name: migration
        image: ghcr.io/5dlabs/agent-docs:latest
        command: ["/usr/local/bin/migrate"]
        args: ["full", "--parallel", "8", "--batch-size", "100"]
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: database-url
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: api-key
        - name: MIGRATION_BATCH_SIZE
          valueFrom:
            configMapKeyRef:
              name: migration-config
              key: batch-size
              optional: true
        - name: MIGRATION_PARALLEL_WORKERS
          valueFrom:
            configMapKeyRef:
              name: migration-config
              key: parallel-workers
              optional: true
        - name: RUST_LOG
          value: "info,doc_server=debug"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: migration-data
          mountPath: /data
          readOnly: true
      volumes:
      - name: migration-data
        configMap:
          name: migration-data
          optional: true
  backoffLimit: 3
  activeDeadlineSeconds: 7200  # 2 hours timeout
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: migration-config
  namespace: default
  labels:
    app: doc-server
    component: migration
data:
  batch-size: "100"
  parallel-workers: "8"
  max-documents: "0"  # 0 = unlimited
  validation-level: "full"