[build]
# Use a local no-op rustc wrapper to avoid missing `sccache` in CI
rustc-wrapper = "scripts/rustc-wrapper.sh"

# Normalize linker on Linux runners where `/usr/local/bin/clang-mold` may not exist
[target.x86_64-unknown-linux-gnu]
linker = "cc"

[target.aarch64-unknown-linux-gnu]
linker = "cc"

