---
name: Auto Format (cargo fmt)

'on':
  push:
    branches: ["**"]

permissions:
  contents: write

jobs:
  format:
    if: >
      ${{ !contains(github.event.head_commit.message, '[skip ci]') &&
      github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Install Rust (stable) with rustfmt
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Run cargo fmt
        run: cargo fmt --all

      - name: Auto-commit formatted changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(fmt): apply cargo fmt [skip ci]"
          commit_user_name: "5DLabs CI"
          commit_user_email: "ci@5dlabs.dev"
          branch: ${{ github.ref_name }}
